version: '3.1'

services:
  demo:
    build:
      context: ./demo
    container_name: time-machine-for-distroless-java8-demo
    restart: always
    environment:
      - TM_LICHOST=45.32.134.232
      - TM_LICPORT=57777
      - TM_LICPASS=qwerty
      - TZ=Asia/Shanghai
      #- TZ=Europe/Amsterdam
    ports:
      - "17800:7800"
    volumes:
      - "./tmdata:/tmdata"
