version: '3.1'

services:
  tm:
    container_name: tm-for-centos8
    image: solutionsoft/timemachine-for-centos8:latest
    restart: always
    environment:
      - TM_LICHOST=192.168.20.112
      - TM_LICPORT=57777
      - TM_LICPASS=docker
    ports:
      - "7800:7800"
    volumes:
      - "./tmdata:/tmdata"
